//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConverterClient.ConverterReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.sliit.lk/", ConfigurationName="ConverterReference.MyConverter")]
    public interface MyConverter {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://web.sliit.lk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://web.sliit.lk/MyConverter/convertCToFRequest", ReplyAction="http://web.sliit.lk/MyConverter/convertCToFResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConverterClient.ConverterReference.convertCToFResponse convertCToF(ConverterClient.ConverterReference.convertCToFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="convertCToF", WrapperNamespace="http://web.sliit.lk/", IsWrapped=true)]
    public partial class convertCToFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double value;
        
        public convertCToFRequest() {
        }
        
        public convertCToFRequest(double value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="convertCToFResponse", WrapperNamespace="http://web.sliit.lk/", IsWrapped=true)]
    public partial class convertCToFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public convertCToFResponse() {
        }
        
        public convertCToFResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyConverterChannel : ConverterClient.ConverterReference.MyConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyConverterClient : System.ServiceModel.ClientBase<ConverterClient.ConverterReference.MyConverter>, ConverterClient.ConverterReference.MyConverter {
        
        public MyConverterClient() {
        }
        
        public MyConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConverterClient.ConverterReference.convertCToFResponse ConverterClient.ConverterReference.MyConverter.convertCToF(ConverterClient.ConverterReference.convertCToFRequest request) {
            return base.Channel.convertCToF(request);
        }
        
        public double convertCToF(double value) {
            ConverterClient.ConverterReference.convertCToFRequest inValue = new ConverterClient.ConverterReference.convertCToFRequest();
            inValue.value = value;
            ConverterClient.ConverterReference.convertCToFResponse retVal = ((ConverterClient.ConverterReference.MyConverter)(this)).convertCToF(inValue);
            return retVal.@return;
        }
    }
}
